### ISSUE TITLE
[BUG] Test 'Create And Delete Transactional Backup' is failed

### ISSUE THREAD

**Issue by KryukovaPolina** [Netcracker/qubership-zookeeper#43]
**Describe the bug**
Test 'Create And Delete Transactional Backup' is failed
Create And Delete Transactional Backup                                | FAIL |
Keyword 'Check That Backup Is Presented' failed after retrying for 30 minutes. The last error was: HTTPError: 404 Client Error: NOT FOUND for url: https://zookeeper-backup-daemon:8443/listbackups/20250630T115352

**To Reproduce**
Install Zookeeper
Template:
```
global:
  name: zookeeper
  secrets:
    zooKeeper:
      adminUsername: "zadmin"
      adminPassword: "zadmin"
      clientUsername: "zclient"
      clientPassword: "zclient"
      additionalUsers: user:pass
    backupDaemon:
      username: "admin"
      password: "admin"
    integrationTests:
      prometheus:
        user: "admin"
        password: "admin"
  tls:
    enabled: true
    cipherSuites: []
    allowNonencryptedAccess: false
    generateCerts:
      enabled: true
      certProvider: cert-manager
      durationDays: 365
      clusterIssuerName: test-clusterissuer
operator:
  securityContext:
    fsGroup: 1000
    runAsUser: 1000
zooKeeper:
  replicas: 3
  storage:
    className:
      - standard
    size: 1Gi
    securityContext:
      fsGroup: 1000
      runAsUser: 1000
  tls:
    enabled: true
backupDaemon:
  install: true
  backupStorage:
    persistentVolumeType: "standalone"
    storageClass: standard
    volumeSize: 1Gi
  securityContext:
    runAsUser: 1000
    fsGroup: 1000
  tls:
    enabled: true
monitoring:
  install: false
  securityContext:
    fsGroup: 1000
    runAsUser: 1000
integrationTests:
  install: true
  tags: "zookeeper"
  timeout: 900
  waitForResult: true
  securityContext:
    fsGroup: 1000
    runAsUser: 1000
```

**Expected behavior**
Test is skipped if persistentVolumeType is "standalone"

**Screenshots**

![Image](https://github.com/user-attachments/assets/ef050725-1a4e-4cb8-9017-c57b65fef511)

**Environment:**
 - Application Version: main
 - K8S Version: 

**Additional context**

**Comment by KryukovaPolina** [comment]
incorrect parameters for tests. Fix: 
```
integrationTests:
  install: true
  tags: "zookeeper_crud"
  timeout: 600
  waitForResult: true
  pvType: "standalone"
  securityContext:
    fsGroup: 1000
    runAsUser: 1000
```
